import React, { type CSSProperties } from 'react';
import { interpolate, spring, useCurrentFrame, useVideoConfig } from 'remotion';
import { beats, pitch } from '@/config/content';
import { sec } from '@/lib/timeline';
export const clamp = (frame:number, from:number, to:number) => interpolate(frame,[from,to],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
export const money = (n:number) => '$'+Math.round(n).toLocaleString('en-US');
export const panel:CSSProperties = {background:'var(--surface)',border:'1px solid var(--line)',borderRadius:12,padding:28};
export const label:CSSProperties = {fontSize:15,letterSpacing:'0.1em',textTransform:'uppercase',color:'var(--muted)',fontWeight:500};
export function Fade({children,at=0,duration=beats.enter,style={}}:{children:React.ReactNode;at?:number;duration?:number;style?:CSSProperties}) {const f=useCurrentFrame(); const p=clamp(f,sec(at),sec(at+duration));return <div style={{opacity:p,transform:`translateY(${12*(1-p)}px)`,...style}}>{children}</div>}
export function Counter({value,at=0,duration=0.8,prefix='',suffix=''}:{value:number;at?:number;duration?:number;prefix?:string;suffix?:string}) {const f=useCurrentFrame();return <>{prefix}{Math.round(value*clamp(f,sec(at),sec(at+duration))).toLocaleString('en-US')}{suffix}</>}
export function Skeleton({height=30,width='100%'}:{height?:number;width?:string|number}) {const f=useCurrentFrame();return <div style={{height,width,borderRadius:8,background:`linear-gradient(100deg,var(--line),var(--bg),var(--line))`,backgroundSize:'200% 100%',backgroundPosition:`${-f*4}% 0`}}/>}
export function LoadingGate({until,children}:{until:number;children:React.ReactNode}) {const f=useCurrentFrame();return f<sec(until)?<div style={{display:'grid',gap:24}}><Skeleton height={120}/><Skeleton height={100}/><Skeleton height={300}/></div>:<>{children}</>}
export function TypingDots(){const f=useCurrentFrame();return <span style={{display:'inline-flex',gap:6,padding:12}}>{[0,1,2].map(i=><i key={i} style={{width:7,height:7,borderRadius:9,background:'var(--muted)',opacity:0.3+0.7*(Math.sin(f/5-i)+1)/2}}/>)}</span>}
export function Typewriter({text,at,end}:{text:string;at:number;end:number}) {const f=useCurrentFrame();return <span style={{whiteSpace:'pre-wrap'}}>{text.slice(0,Math.floor(text.length*clamp(f,sec(at),sec(end))))}{f<sec(end)?'▌':''}</span>}
export function Avatar({name,color='var(--ink)'}:{name:string;color?:string}){return <span style={{width:42,height:42,borderRadius:'50%',background:color,color:'var(--surface)',display:'inline-flex',alignItems:'center',justifyContent:'center',fontSize:18,fontWeight:600,flexShrink:0}}>{name[0]}</span>}
export function Pill({children,positive=false}:{children:React.ReactNode;positive?:boolean}){return <span style={{display:'inline-flex',border:'1px solid var(--line)',borderRadius:30,padding:'6px 12px',fontSize:14,color:positive?'var(--positive)':'var(--muted)',background:'var(--surface)'}}>{children}</span>}
export function Button({children,action}:{children:React.ReactNode;action:string}){return <button tabIndex={-1} data-demo-action={action} style={{background:'var(--accent)',color:'var(--ink)',border:0,borderRadius:9,padding:'18px 28px',fontSize:20,fontWeight:600}}>{children}</button>}
export function Cursor({x,y,at,fromX=x+180,fromY=y+140}:{x:number;y:number;at:number;fromX?:number;fromY?:number}){const f=useCurrentFrame();const p=clamp(f,sec(at-beats.enter),sec(at));const after=f-sec(at);if(f<sec(at-beats.enter)||after>sec(beats.typing))return null;return <div style={{position:'absolute',left:fromX+(x-fromX)*p,top:fromY+(y-fromY)*p,zIndex:40,pointerEvents:'none'}}>{after>=0&&<div style={{position:'absolute',width:60,height:60,left:-30,top:-30,border:'3px solid var(--accent)',borderRadius:'50%',transform:`scale(${1+after/10})`,opacity:1-after/sec(beats.typing)}}/>}<svg width="34" height="42" viewBox="0 0 34 42"><path d="M3 2L28 25L17 26L12 38Z" fill="var(--ink)" stroke="var(--surface)" strokeWidth="3"/></svg></div>}
export function Drawer({children,at,width=850}:{children:React.ReactNode;at:number;width?:number}){const f=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({fps,frame:f-sec(at),config:{damping:22}});return <aside style={{position:'absolute',right:0,top:0,bottom:0,width,background:'var(--surface)',borderLeft:'1px solid var(--line)',padding:42,transform:`translateX(${(1-p)*100}%)`,boxShadow:'-16px 0 40px #11111108'}}>{children}</aside>}
export function Heading({title,eyebrow=pitch.labels.overview}:{title:string;eyebrow?:string}){return <div style={{marginBottom:30}}><div style={label}>{eyebrow}</div><h1 style={{fontSize:48,lineHeight:1.1,fontWeight:500,letterSpacing:'-0.035em',margin:'14px 0 0'}}>{title}</h1></div>}
